---
board: 'Services: DevOps Engineering'
group: 'GitHub <> Rally Integration'
columns:
  github_link:
    column_id: link
    status_colum: status
  assignee:
    column_id: person
    values:
      - name_or_id: DevOps Engineering
        assignee_kind: team
      - name_or_id: primetheus
        assignee_kind: person
  tags:
    - column_id: tags1
      tag_name: GitHub
  status:
    - column_id: status
      column_label: To Do
