---
#####################################
# Docker compose for Rally + GitHub #
#####################################

###########
# Version #
###########
version: '3.3'

####################
# Set the services #
####################
services:
    rally:
        # Set the open ports
        ports:
            - '3000:3000'
        # Set to restart on error
        restart: always
        # Set logging informatgion
        logging:
            options:
                max-size: 1g
        # Start the image
        image: github/rally
