name: Create item in monday.com

on:
  issues:
    types: [opened, reopened, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  monday:
    name: Monday.com 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: github/monday-action
        path: actions
        ssh-key: '${{ secrets.MONDAY_DEPLOY_KEY }}'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade moncli pyyaml
    - name: Create the item in Monday
      run: python actions/monday.py
      env:
        MONDAY_USERNAME: '${{ secrets.MONDAY_USERNAME }}'
        MONDAY_API_KEY_V1: '${{ secrets.MONDAY_API_KEY_V1 }}'
        MONDAY_API_KEY_V2: '${{ secrets.MONDAY_API_KEY_V2 }}'
